ci: Fix examples workflow [skip tests] (#4141)
Following are the updates that have been done as a part of this PR.

1. Set current working directory as container mount source.
2. Use released PyFluent and Visualization packages in dependencies.
3. `lunar_lander_thermal.py` executes for 25.2 version only. A bug is
already reported for 26.1.
4. `conjugate_heat_transfer.py` is skipped due to an error from
visualization package. https://github.com/ansys/pyfluent/issues/4157 It
will be reactivated after fixing this issue.
5. `modeling_ablation.py` is skipped due to the unavailability of hsf
library but verified that it works fine locally.

Examples workflow -
https://github.com/ansys/pyfluent/actions/runs/15749216353

---------

Co-authored-by: pyansys-ci-bot <92810346+pyansys-ci-bot@users.noreply.github.com>

diff --git a/.github/workflows/execute-examples-weekly.yml b/.github/workflows/execute-examples-weekly.yml
--- a/.github/workflows/execute-examples-weekly.yml
+++ b/.github/workflows/execute-examples-weekly.yml
@@ -15,12 +15,12 @@ env:
   ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
   PYFLUENT_TIMEOUT_FORCE_EXIT: 30
   PYFLUENT_LAUNCH_CONTAINER: 1
+  PYFLUENT_VIZ_BLOCKING: 1
   PYFLUENT_LOGGING: "DEBUG"
   PYFLUENT_WATCHDOG_DEBUG: "OFF"
   PYFLUENT_HIDE_LOG_SECRETS: 1
   PYTHON_VERSION: "3.12"
   PYFLUENT_SKIP_API_UPGRADE_ADVICE: 1
-  PYFLUENT_CONTAINER_MOUNT_SOURCE: "/home/ansys/Downloads/ansys_fluent_core_examples"
 
 jobs:
   execute_examples:
@@ -51,18 +51,6 @@ jobs:
           restore-keys: |
             Python-${{ runner.os }}-${{ env.PYTHON_VERSION }}
 
-      - name: Add version information
-        run: make version-info
-
-      - name: Install pyfluent
-        run: make install
-
-      - name: Retrieve PyFluent version
-        run: |
-          echo "PYFLUENT_VERSION=$(python -c "from ansys.fluent.core import __version__; print(); print(__version__)" | tail -1)" >> $GITHUB_OUTPUT
-          echo "PYFLUENT version is: $(python -c "from ansys.fluent.core import __version__; print(); print(__version__)" | tail -1)"
-        id: version
-
       - name: Login to GitHub Container Registry
         uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
         with:
@@ -70,28 +58,27 @@ jobs:
           username: ansys-bot
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Pull Fluent docker image
-        run: make docker-pull
+      - name: Pull Fluent docker image if not present
+        run: |
+          if ! docker image inspect fluent:${{ matrix.image-tag }} > /dev/null 2>&1; then
+            echo "Image not found locally, pulling..."
+            make docker-pull
+          else
+            echo "Image already exists locally, skipping pull."
+          fi
         env:
           FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
 
-      - name: Run API codegen
+      - name: Install Dependencies
         run: |
           sudo mkdir -p /home/ansys/Downloads/ansys_fluent_core_examples
           sudo chmod a+rwx /home/ansys/Downloads/ansys_fluent_core_examples
-          pip install ansys-fluent-visualization==0.18.dev0
-          make api-codegen
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
-      - name: Print Fluent version info
-        run: |
-          cat src/ansys/fluent/core/generated/fluent_version_${{ matrix.version }}.py
-
-      - name: Install again after codegen
-        run: |
-          rm -rf dist
-          make install > /dev/null
+          sudo apt update
+          sudo apt install libegl1
+          pip install ansys-fluent-core>=0.32.1
+          pip install ansys-fluent-core[reader]
+          pip install ansys-fluent-visualization==0.21.dev1
+          pip install xgboost scikit-learn tensorflow seaborn plotly numpy pandas
 
       - name: Execute Examples
         run: |
@@ -100,89 +87,110 @@ jobs:
         env:
           FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
 
-      - name: Execute ahmed_body_workflow.py
-        run: |
-          python examples/00-fluent/ahmed_body_workflow.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
-      - name: Execute brake.py
-        run: |
-          python examples/00-fluent/brake.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
-      - name: Execute conjugate_heat_transfer.py
-        run: |
-          python examples/00-fluent/conjugate_heat_transfer.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
-      - name: Execute DOE_ML.py
-        run: |
-          python examples/00-fluent/DOE_ML.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
-      - name: Execute exhaust_system_settings_api.py
-        run: |
-          python examples/00-fluent/exhaust_system_settings_api.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
-      - name: Execute external_compressible_flow.py
-        run: |
-          python examples/00-fluent/external_compressible_flow.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
-      - name: Execute lunar_lander_thermal.py
-        run: |
-          python examples/00-fluent/lunar_lander_thermal.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
+      # ~1 minute
       - name: Execute mixing_elbow_settings_api.py
         run: |
           python examples/00-fluent/mixing_elbow_settings_api.py
         env:
           FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
 
-      - name: Execute modeling_ablation.py
-        run: |
-          python examples/00-fluent/modeling_ablation.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
-      - name: Execute modeling_cavitation.py
-        run: |
-          python examples/00-fluent/modeling_cavitation.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
-      - name: Execute parametric_static_mixer_1.py
-        run: |
-          python examples/00-fluent/parametric_static_mixer_1.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
-      - name: Execute radiation_headlamp.py
-        run: |
-          python examples/00-fluent/radiation_headlamp.py
-        env:
-          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
-
+      # ~1 minute
       - name: Execute species_transport.py
         run: |
           python examples/00-fluent/species_transport.py
         env:
           FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
 
+      # ~1 minute
+      - name: Execute modeling_cavitation.py
+        run: |
+          python examples/00-fluent/modeling_cavitation.py
+        env:
+          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # ~3 minutes
+      - name: Execute ahmed_body_workflow.py
+        run: |
+          python examples/00-fluent/ahmed_body_workflow.py
+        env:
+          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # ~4 minutes
+      - name: Execute exhaust_system_settings_api.py
+        run: |
+          python examples/00-fluent/exhaust_system_settings_api.py
+        env:
+          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # ~4 minutes
+      - name: Execute parametric_static_mixer_1.py
+        run: |
+          python examples/00-fluent/parametric_static_mixer_1.py
+        env:
+          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # ~5 minutes
+      - name: Execute brake.py
+        run: |
+          python examples/00-fluent/brake.py
+        env:
+          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # ~5 minutes
+      - name: Execute external_compressible_flow.py
+        run: |
+          python examples/00-fluent/external_compressible_flow.py
+        env:
+          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # ~15 minutes
+      - name: Execute radiation_headlamp.py
+        run: |
+          python examples/00-fluent/radiation_headlamp.py
+        env:
+          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # ~17 minutes
+      - name: Execute DOE_ML.py
+        run: |
+          python examples/00-fluent/DOE_ML.py
+        env:
+          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # ~17 minutes
+      - name: Execute frozen_rotor_workflow.py
+        run: |
+          python examples/00-fluent/frozen_rotor_workflow.py
+        env:
+          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # ~26 minutes, hangs for v26.1.0
+      - name: Execute lunar_lander_thermal.py
+        run: |
+          python examples/00-fluent/lunar_lander_thermal.py
+        env:
+          FLUENT_IMAGE_TAG: v25.2.0
+
+      # ~40 minutes
       - name: Execute tyler_sofrin_modes.py
         run: |
           python examples/00-fluent/tyler_sofrin_modes.py
         env:
           FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # https://github.com/ansys/pyfluent/issues/4157
+      # - name: Execute conjugate_heat_transfer.py
+      #   run: |
+      #     python examples/00-fluent/conjugate_heat_transfer.py
+      #   env:
+      #     FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
+
+      # RuntimeError: Unable to load hsf library and requires separate license.
+      # - name: Execute modeling_ablation.py
+      #   run: |
+      #     python examples/00-fluent/modeling_ablation.py
+      #   env:
+      #     FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
 
       - name: Cleanup previous docker containers
         if: always()
